### ISSUE TITLE
本地复现

### ISSUE THREAD

**Issue by firmianay** [zh-explorer/hctf2016-brop#1]
师傅这个题出的是真的好，能学到东西，但是我不知道在本地怎么把它跑起来，求指点。直接socat好像是不行

**Comment by zh-explorer** [comment]
socat是可以的。远程的环境和socat差不多。不过当初为了节省服务器压力，远程的守护脚本会在当前程序退出之后直接重启而不断开连接，这样就无需重新连接服务器了。而socat会在进程退出之后断开连接。这个是主要的区别
有其他问题可以直接联系我邮箱hsadkhk@gmail.com
